version: '3'

services:

  api:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      MIX_ENV: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: librarydb
      POSTGRES_HOSTNAME: postgres
      PORT: 4000

    ports:
      - "4000:4000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: librarydb

